spring:
  datasource:
    url:
    username:
    password:
    initialization-mode: always
    dbcp2:
      validation-query: SELECT 1
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
jwt:
  header: Authorization
  secret:
  token-validity-in-seconds: 86400

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            BasicBinder: TRACE